// Feature 021: Analysis Data Models
// Defines all data structures for skill analysis results

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

/// Main analysis result container
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillAnalysisResult {
    pub analysis_id: String,
    pub skill_name: String,
    pub skill_path: String,
    pub timestamp: DateTime<Utc>,
    pub status: AnalysisStatus,
    pub progress: u8,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub spec_compliance: Option<SpecCompliance>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pda_analysis: Option<PDAAnalysis>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub security_review: Option<SecurityReview>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub trigger_suggestions: Option<Vec<TriggerSuggestion>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub link_validation: Option<LinkValidation>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AnalysisStatus {
    Running,
    Completed,
    Failed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpecCompliance {
    pub score: u8,
    pub violations: Vec<Violation>,
    pub warnings: Vec<Warning>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Violation {
    pub rule: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fix_suggestion: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line_number: Option<usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Warning {
    pub rule: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub recommendation: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PDAAnalysis {
    pub score: u8,
    pub token_estimate: usize,
    pub tier_breakdown: TierBreakdown,
    pub recommendations: Vec<String>,
    pub suggested_structure: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ai_insights: Option<Vec<String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TierBreakdown {
    pub metadata_tokens: usize,
    pub orchestrator_tokens: usize,
    pub resource_tokens: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityReview {
    pub score: u8,
    pub unused_permissions: Vec<String>,
    pub high_risk_permissions: Vec<RiskFlag>,
    pub minimum_required: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskFlag {
    pub permission: String,
    pub risk_level: RiskLevel,
    pub explanation: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mitigation: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RiskLevel {
    Critical,
    High,
    Medium,
    Low,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TriggerSuggestion {
    pub keyword: String,
    pub relevance_score: u8,
    pub explanation: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LinkValidation {
    pub total_links: usize,
    pub valid_links: usize,
    pub broken_links: Vec<BrokenLink>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BrokenLink {
    pub url: String,
    pub line_number: usize,
    pub error: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CLIDetectionResult {
    pub claude_available: bool,
    pub opencode_available: bool,
    pub gemini_available: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub claude_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub opencode_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gemini_path: Option<String>,
}

/// Cached analysis result with expiry timestamp
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CachedResult {
    pub result: SkillAnalysisResult,
    pub expires_at: DateTime<Utc>,
}

/// Status of an individual analyzer
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AnalyzerStatus {
    Pending,
    Running,
    Complete,
    Error,
}

/// Report generated by an analyzer (FR-009)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalyzerReport {
    /// Name of the analyzer (e.g., "Spec Compliance", "PDA Analysis")
    pub analyzer_name: String,
    /// Human-readable markdown report
    pub markdown: String,
    /// Structured JSON data (embedded at end of markdown)
    pub json_data: serde_json::Value,
    /// Status of the analyzer
    pub status: AnalyzerStatus,
    /// Duration in milliseconds
    pub duration_ms: u64,
    /// Score 0-100 (if applicable)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub score: Option<u8>,
}

/// Status of all analyzers for an analysis run
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisProgressStatus {
    pub analysis_id: String,
    pub skill_name: String,
    pub overall_status: AnalysisStatus,
    pub spec: AnalyzerStatus,
    pub pda: AnalyzerStatus,
    pub permissions: AnalyzerStatus,
    pub triggers: AnalyzerStatus,
    pub links: AnalyzerStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    #[test]
    fn test_analysis_status_serialization() {
        let status = AnalysisStatus::Running;
        let json = serde_json::to_string(&status).unwrap();
        assert_eq!(json, "\"running\"");

        let status: AnalysisStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(status, AnalysisStatus::Running);
    }

    #[test]
    fn test_risk_level_serialization() {
        let level = RiskLevel::Critical;
        let json = serde_json::to_string(&level).unwrap();
        assert_eq!(json, "\"critical\"");

        let level: RiskLevel = serde_json::from_str(&json).unwrap();
        assert_eq!(level, RiskLevel::Critical);
    }

    #[test]
    fn test_skill_analysis_result_serialization() {
        let result = SkillAnalysisResult {
            analysis_id: "test-123".to_string(),
            skill_name: "test-skill".to_string(),
            skill_path: "/path/to/skill".to_string(),
            timestamp: Utc::now(),
            status: AnalysisStatus::Completed,
            progress: 100,
            spec_compliance: None,
            pda_analysis: None,
            security_review: None,
            trigger_suggestions: None,
            link_validation: None,
            error: None,
        };

        let json = serde_json::to_string(&result).unwrap();
        let deserialized: SkillAnalysisResult = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.analysis_id, "test-123");
        assert_eq!(deserialized.skill_name, "test-skill");
        assert_eq!(deserialized.status, AnalysisStatus::Completed);
        assert_eq!(deserialized.progress, 100);
    }

    #[test]
    fn test_spec_compliance_full_serialization() {
        let compliance = SpecCompliance {
            score: 85,
            violations: vec![
                Violation {
                    rule: "missing_name".to_string(),
                    message: "Skill is missing required 'name' field".to_string(),
                    fix_suggestion: Some("Add 'name: my-skill' to frontmatter".to_string()),
                    line_number: Some(1),
                },
            ],
            warnings: vec![
                Warning {
                    rule: "missing_triggers".to_string(),
                    message: "No triggers section found".to_string(),
                    recommendation: Some("Add ## Triggers section".to_string()),
                },
            ],
        };

        let json = serde_json::to_string(&compliance).unwrap();
        let deserialized: SpecCompliance = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.score, 85);
        assert_eq!(deserialized.violations.len(), 1);
        assert_eq!(deserialized.violations[0].rule, "missing_name");
        assert_eq!(deserialized.warnings.len(), 1);
    }

    #[test]
    fn test_pda_analysis_serialization() {
        let pda = PDAAnalysis {
            score: 75,
            token_estimate: 3500,
            tier_breakdown: TierBreakdown {
                metadata_tokens: 200,
                orchestrator_tokens: 1500,
                resource_tokens: 1800,
            },
            recommendations: vec![
                "Move detailed examples to references/ directory".to_string(),
            ],
            suggested_structure: vec![
                "skill.md (orchestrator, ~1500 tokens)".to_string(),
                "references/examples.md (~1800 tokens)".to_string(),
            ],
            ai_insights: None,
        };

        let json = serde_json::to_string(&pda).unwrap();
        let deserialized: PDAAnalysis = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.score, 75);
        assert_eq!(deserialized.token_estimate, 3500);
        assert_eq!(deserialized.tier_breakdown.metadata_tokens, 200);
        assert_eq!(deserialized.recommendations.len(), 1);
    }

    #[test]
    fn test_security_review_serialization() {
        let review = SecurityReview {
            score: 60,
            unused_permissions: vec!["Write".to_string()],
            high_risk_permissions: vec![
                RiskFlag {
                    permission: "Bash".to_string(),
                    risk_level: RiskLevel::High,
                    explanation: "Bash with Write can modify files".to_string(),
                    mitigation: Some("Remove Write permission if not needed".to_string()),
                },
            ],
            minimum_required: vec!["Read".to_string(), "Grep".to_string()],
        };

        let json = serde_json::to_string(&review).unwrap();
        let deserialized: SecurityReview = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.score, 60);
        assert_eq!(deserialized.unused_permissions.len(), 1);
        assert_eq!(deserialized.high_risk_permissions[0].risk_level, RiskLevel::High);
    }

    #[test]
    fn test_cli_detection_result_serialization() {
        let detection = CLIDetectionResult {
            claude_available: true,
            opencode_available: false,
            gemini_available: false,
            claude_path: Some("/usr/local/bin/claude".to_string()),
            opencode_path: None,
            gemini_path: None,
        };

        let json = serde_json::to_string(&detection).unwrap();
        let deserialized: CLIDetectionResult = serde_json::from_str(&json).unwrap();

        assert!(deserialized.claude_available);
        assert!(!deserialized.opencode_available);
        assert!(!deserialized.gemini_available);
        assert_eq!(deserialized.claude_path.as_deref(), Some("/usr/local/bin/claude"));
        assert!(deserialized.opencode_path.is_none());
        assert!(deserialized.gemini_path.is_none());
    }

    #[test]
    fn test_cached_result_serialization() {
        let now = Utc::now();
        let cached = CachedResult {
            result: SkillAnalysisResult {
                analysis_id: "cached-123".to_string(),
                skill_name: "cached-skill".to_string(),
                skill_path: "/path".to_string(),
                timestamp: now,
                status: AnalysisStatus::Completed,
                progress: 100,
                spec_compliance: None,
                pda_analysis: None,
                security_review: None,
                trigger_suggestions: None,
                link_validation: None,
                error: None,
            },
            expires_at: now + chrono::Duration::hours(24),
        };

        let json = serde_json::to_string(&cached).unwrap();
        let deserialized: CachedResult = serde_json::from_str(&json).unwrap();

        assert_eq!(deserialized.result.analysis_id, "cached-123");
        assert!(deserialized.expires_at > now);
    }

    #[test]
    fn test_optional_fields_not_serialized_when_none() {
        let result = SkillAnalysisResult {
            analysis_id: "test".to_string(),
            skill_name: "test".to_string(),
            skill_path: "/test".to_string(),
            timestamp: Utc::now(),
            status: AnalysisStatus::Running,
            progress: 50,
            spec_compliance: None,
            pda_analysis: None,
            security_review: None,
            trigger_suggestions: None,
            link_validation: None,
            error: None,
        };

        let json = serde_json::to_string(&result).unwrap();

        // Verify optional fields are not present in JSON
        assert!(!json.contains("spec_compliance"));
        assert!(!json.contains("pda_analysis"));
        assert!(!json.contains("security_review"));
        assert!(!json.contains("error"));
    }
}
